# Vercel Build Configuration
# Ensure React app is built correctly

[build]
  command = "cd ridewayz-app && npm install && npm run build"
  publish = "ridewayz-app/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200